### ISSUE TITLE
accountBalance example

### ISSUE THREAD

**Issue by gitkornel** [subatomicdev/binance-futures-cpp#2]
Hello,

I've been trying to make `accountBalance` work, but so far no success.

Best regards.

My current code (that doesn't work):
 ```
std::vector<pplx::task<bfcpp::NewOrderResult>> results;
        results.reserve(1);

        results.emplace_back(std::move(market.accountBalance()));

        pplx::when_all(std::begin(results), std::end(results)).wait();

        std::stringstream account_balance;

        for (auto &task : results)
        {
            bfcpp::NewOrderResult result = task.get();

            account_balance << result.response["availableBalance"];
        }
```

**Comment by subatomicdev** [comment]
Hi
The accountBalance() returns an ```AccountBalance``` struct, not a ```pplx::task```.  

You should change to something like:

- **Remember you must supply your API and secret keys for account balance**
- **Change UsdFuturesTestMarket to UsdFuturesMarket if you want the real/live exchange**

```
UsdFuturesTestMarket market{ ApiAccess {"YOUR API KEY", "YOUR SECRET KEY" } };  // TODO you must supply a api and secret key for account balance

AccountBalance result = market.accountBalance();
  
std::stringstream account_balance;

// for each 'asset'
for (auto& account : result.balances)
{
  account_balance << "\nasset: " << account["asset"] << " has balance " << account["availableBalance"];
}

std::cout << account_balance.str();
```

![image](https://user-images.githubusercontent.com/74328784/115050543-c24c4b00-9ed3-11eb-93d4-2266275b6ce1.png)


You can use the code from:   bfcpp\bfcpptest\bfcpptest.cpp which shows how to use accountBalance().

**Comment by gitkornel** [comment]
Thank you!

That works, how would I go about only getting the balance of USDT for example?

**Comment by subatomicdev** [comment]
You can use the following:

```cpp
string getAvailableBalance(const AccountBalance& accounts, const string& assetName)
{
  string balance;

  auto entry = std::find_if(accounts.balances.cbegin(), accounts.balances.cend(), [&accounts, &assetName](auto& balance) { return balance.find("asset")->second == assetName; });
  if (entry != accounts.balances.cend())
  {
    balance = entry->at("availableBalance");
  }
  return balance;
}



// ... somewhere else in your code ...

UsdFuturesTestMarket market{ ApiAccess {"YOUR API KEY", "YOUR SECRET KEY" } };  // TODO you must supply a api and secret key for account balance

AccountBalance result = market.accountBalance();

if (string usdtBalanceString = getAvailableBalance(result, "USDT"); !usdtBalanceString.empty())
{
  std::cout << "\nusdtBalanceString=" << usdtBalanceString ;
}
```

**Comment by gitkornel** [comment]
> You can use the following:
> 
> ```c++
> string getAvailableBalance(const AccountBalance& accounts, const string& assetName)
> {
>   string balance;
> 
>   auto entry = std::find_if(accounts.balances.cbegin(), accounts.balances.cend(), [&accounts, &assetName](auto& balance) { return balance.find("asset")->second == assetName; });
>   if (entry != accounts.balances.cend())
>   {
>     balance = entry->at("availableBalance");
>   }
>   return balance;
> }
> 
> 
> 
> // ... somewhere else in your code ...
> 
> UsdFuturesTestMarket market{ ApiAccess {"YOUR API KEY", "YOUR SECRET KEY" } };  // TODO you must supply a api and secret key for account balance
> 
> AccountBalance result = market.accountBalance();
> 
> if (string usdtBalanceString = getAvailableBalance(result, "USDT"); !usdtBalanceString.empty())
> {
>   std::cout << "\nusdtBalanceString=" << usdtBalanceString ;
> }
> ```

Awesome, it works, thank you so much!
