### ISSUE TITLE
API KEY for real trading doesn't work

### ISSUE THREAD

**Issue by cryptonec-dev** [subatomicdev/binance-futures-cpp#3]
Testnet API key works totally fine. It's possible to get account information/create orders/etc.
But API key for the real binance futures doesn't work. I can't even get information about account balance, it returns "Found 0 balances".
- I have enabled all the features for the corresponding key, except withdrawals and universal transfer. 
- I have a binance futures account.
- API key is 100% correct.
- The code itself is also correct, it works fine with Testnet API key.

What do I need to change in code to get access to real futures?

**Comment by cryptonec-dev** [comment]
Oops. Seems like I've found the thing I need to change :)
UsdFuturesTestMarket -> UsdFuturesMarket

**Comment by subatomicdev** [comment]
Hi,  yes use the ```UsdFuturesMarket```.  Having separate classes allows me to restrict functionality that may not be available on both (and it takes more effort to switch from Testnet to the live exchange).
